### ISSUE TITLE
Need awesomplete-avoid-xss with versison 1.1.4

### ISSUE THREAD

**Issue by RajasekarPR** [jcbrand/awesomplete#2]
Hi,

I need this package bu the version is still 1.1.2. Awesomplete released the latest version 1.1.4

Can you release the awesomplete-avoid-xss package with merging their changes. Do the needful please.

**Comment by jcbrand** [comment]
Sorry, I'm no longer maintaining this package and it won't extend beyond version 1.1.2.

If you really need the XSS protection added here, then I suggest you talk to the maintainers of Awesomplete and try to convince them to put the changes there, or otherwise you can maintain your own fork.
